(defun calcul (expr)
  (cond
    ((numberp expr) expr)
    ((and (listp expr) (eq '+ (car expr)))
     (+ (calcul (cadr expr)) (calcul (caddr expr))))
    ((and (listp expr) (eq '- (car expr)))
     (- (calcul (cadr expr)) (calcul (caddr expr))))
    ((and (listp expr) (eq '* (car expr)))
     (* (calcul (cadr expr)) (calcul (caddr expr))))
    ((and (listp expr) (eq '/ (car expr)))
     (/ (calcul (cadr expr)) (calcul (caddr expr))))
    (t (error "Mauvaise expression"))
   )
)
(print (calcul '(+ 5 5))) 
