(load "vm-registers.lisp")
(load "vm-memory.lisp")
(load "vm-core.lisp")
(load "vm-instructions.lisp")
(load "vm-loader.lisp")
(load "vm-runner.lisp")
(load "vm-utils.lisp")

(defparameter *current-vm* (vm-make :memory-size 1024 :name "Test VM"))
(vm-load '((LOAD (:CONST 10) R0)
           (LOAD (:CONST 20) R1)
           (CMP R0 R1)
           (JLT LESS)
           (LOAD (:CONST 100) R2)
           (JMP END)
           (LABEL LESS)
           (LOAD (:CONST 8) R2)
           (LABEL END)
           (HALT)))
(vm-run)
(print-registers *current-vm*)